backend:
  name: github
  branch: main
  repo: professorsugoi/DEVILISH-WIKI

media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

# cloudinary requires endpoint to be exposed. this is not enough to compromise the account.
media_library:
  name: cloudinary
  config:
    cloud_name: dzbuflwjv
    api_key: 524222544269166

collections:
- name: docs
  label: "docs"
  folder: docs
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{slug}}" # Filename template
  fields:
    - { label: Title, name: title, widget: string }
    - { label: Body, name: body, widget: markdown }
    - { label: Slug, name: slug, widget: string }

    - label: "Tags"
      name: "tags"
      widget: "select"
      multiple: true
      min: 1
      max: 3
      options: ["Devil", "World", "Lore"]
      default: ["Devil"]

    - label: "Keywords" # SEO keywords
      name: "keywords"
      widget: "select"
      multiple: true
      min: 0
      max: 3
      options: ["Devilish", "World", "Lore"]
      default: [""]

    - label: "Last modified"
      name: "last modified"
      widget: "date"
      default: ""
      date_format: "MMM DD YYYY"
      format: "L"

- name: blog
  label: "blog"
  folder: blog
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { label: Title, name: title, widget: string }
    - { label: Body, name: body, widget: markdown }
    - { label: Slug, name: slug, widget: string }

    - label: "Tags"
      name: "tags"
      widget: "list"

    - label: "Authors"
      name: "authors"
      widget: "list"
      fields:
        - { label: Name, name: name, widget: string }
        - { label: Title, name: title, widget: string }